### ISSUE TITLE
Does jupyter-dash support https?

### ISSUE THREAD

**Issue by kdzhao** [plotly/jupyter-dash#77] opened 2022-03-04 02:10 UTC
I noticed it works good on my local environment, but in the actual environment, nothing shows up in the UI. And by using F12 on my Chrome, I see this error (I was trying to use port 2000 in this example): 

The page at 'https://myserver/user/myid/lab/tree/myid/my-notebook.ipynb' was loaded over HTTPS, but requested an insecure frame 'http://myserver:2000/'. This request has been blocked; the content must be served over HTTPS.

And checking the docs here, I don't see https is mentioned anywhere. 

Thanks

**Comment by umutkaya-ugent** [comment] 2022-04-30 21:51
I can confirm that it can work with https (at least on z2jh). It works over the extension jupyter-server-proxy, which redirects ports via https://myserver/user/myid/proxy/<proxy-no>.

**Comment by Blubbaa** [comment] 2023-06-27 12:58
Having the same issue it seems. I am trying to get an embedded plot in an iFrame working in some production/server environment.

Although I am using some additional packages (`voila` for serving the notebook, `plotly, plotly-resampler` for the figures), it seems like under the hood the problem is a JupyterDash server which should be serving the iFrame content via https.

Did anyone get this working with https?

**Comment by T4rk1n** [comment] 2023-06-27 13:37
JupyterDash has been merged with main Dash package, if this is still an issue after trying the following, please open a new one on https://github.com/plotly/dash.

Without configuration, http is always used and the server_url will be `http://{host}.{port}`. This can be changed by:

- Setting `DASH_DOMAIN_BASE`, the url will then be formatted as `https://{domain_base}`.
- Calling `JupyterDash.infer_jupyter_proxy_config` could work if it can the proxy server_url from it, need the base notebook extension or jupyterlab extension built and active.
- Set parameter `server_url` for `JupyterDash.run`  or `jupyter_server_url` for `Dash.run` to use that url as is.

**Closed by T4rk1n** 2023-06-27 13:37 UTC
